### PR TITLE
[INLONG-10883][SDK] Transform SQL support InitCap function

### LINKED ISSUE #10883: [Feature][SDK] Transform SQL support InitCap function
### Description

- parent issue https://github.com/apache/inlong/issues/10796
- INITCAP(string)
- Returns a new form of STRING with the first character of each word converted to uppercase and the rest characters to lowercase. Here a word means a sequences of alphanumeric characters.

### Use case

_No response_

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by MOONSakura0614**
Fixes #10883 

### Motivation

Add a function class: InitCapFunction and its unit test.
- initcap(string)
Returns a new form of STRING with the first character of each word converted to uppercase and the rest characters to lowercase. Here a word means a sequences of alphanumeric characters.

### Verifying this change

*(Please pick either of the following options)*

- [ ] This change is a trivial rework/code cleanup without any test coverage.

- [x] This change is already covered by existing tests, such as:
  *(please describe tests)*

- [ ] This change added tests and can be verified as follows:

  *(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
  - If a feature is not applicable for documentation, explain why?
  - If a feature is not documented yet in this PR, please create a follow-up issue for adding the documentation

### CODE REVIEW

**Review by aloyszhang — DISMISSED** [review]

**Review by luchunliang — DISMISSED** [review]

**Comment by aloyszhang** [comment]
plz rebase the master to resolve the conflict

**Review by yfsn666 — APPROVED** [review]

**Comment by dockerzhang** [comment]
@MOONSakura0614 please fix the conflicts and failed workflows.

**Comment by MOONSakura0614** [comment]
> @MOONSakura0614 please fix the conflicts and failed workflows.

already resolve the conflicts and force push. 
Your careful review is much appreciated.

**Comment by MOONSakura0614** [comment]
> plz rebase the master to resolve the conflict

done and thank you for checking again.

**Review by luchunliang — APPROVED** [review]

**Comment by dockerzhang** [comment]
@MOONSakura0614 please fix the conflicts and failed workflows.

**Comment by MOONSakura0614** [comment]
> @MOONSakura0614 please fix the conflicts and failed workflows.

already fix the conflicts and failed workflows by force-push.

**Review by aloyszhang — APPROVED** [review]

**Comment by MOONSakura0614** [comment]
@aloyszhang Sorry for another review. Because I forget the pr "return "" if param string is null", I expected "result = null" in unit test which caused failure.
Thank you for your kind checking~

**Review by luchunliang — DISMISSED** [review]

**Comment by aloyszhang** [comment]
You  should rebase the master branch and then force push you branch

**Comment by MOONSakura0614** [comment]
> You should rebase the master branch and then force push you branch

solved

**Review by aloyszhang — APPROVED** [review]

**Review by luchunliang — APPROVED** [review]

**Pull request merged**
