### PR TITLE
[INLONG-11000][SDK] Add XML formatted data source for Transform

### LINKED ISSUE #11000: [Feature][SDK] Add XML formatted data source for Transform
### Description

- parent issue #10796

Add parsing for data source types such as the following. And support the conversion of XML format data to other types of structures.
```xml
<Message>
    <sid>sid1</sid>
    <packageID>pid1</packageID>
    <msgs>
        <msg>
            <data>value1</data>
            <msgTime>1713243918000</msgTime>
        </msg>
        <msg>
            <data>value2</data>
            <msgTime>1713243918000</msgTime>
        </msg>
    </msgs>
</Message>

```

### Use case

_No response_

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by Zkplo**
Fixes #11000 

### Motivation

Add several classes: XmlSourceInfo, XmlNode, XmlSourceData, XmlSourceDecoder. Modified SourceDecoderFactory class. Also, add the corresponding unit test codes.

### Verifying this change

*(Please pick either of the following options)*

- [ ] This change is a trivial rework/code cleanup without any test coverage.

- [x] This change is already covered by existing tests, such as:
  *(please describe tests)*

- [ ] This change added tests and can be verified as follows:

  *(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### CODE REVIEW

**Comment by dockerzhang** [comment]
@Zkplo please fix the failed workflows and UTs.

**Review by luchunliang — APPROVED** [review]

**Comment by aloyszhang** [comment]
Please resolve the conflict

**Comment by Zkplo** [comment]
> Please resolve the conflict请解决冲突

done.

**Review by luchunliang — APPROVED** [review]

**Comment by dockerzhang** [comment]
@Zkplo please rebase from the master branch to fix the failed workflow.

**Comment by Zkplo** [comment]
> @Zkplo please rebase from the master branch to fix the failed workflow.请从 master 分支变基以修复失败的工作流程。

done.

**Review by dockerzhang — APPROVED** [review]

**Review by aloyszhang — APPROVED** [review]

**Pull request merged**
