### PR TITLE
[INLONG-11199][Sort] Integrate Grafana Loki for connectors

### LINKED ISSUE #11199: [Feature][Sort] Integrate log management systems for connectors
### Description

- Parent issue #10798 
- Related issue #11065 

Currently, the log information generated by sort-connector (in flink taskmanagers) has been centrally output to opentelemetry-collector, **but it is inefficient to view and manage logs in the console of opentelemetry-collector**.

So we need to find an excellent open source log system to collect and manage logs.

### Use case

Integrate a log management system to achieve the following functions:

1. Log collection
2. Log management
3. Log filtering

There are currently two alternatives: [Grafana Loki](https://grafana.com/docs/loki/latest/) and [Signoz](https://signoz.io/)

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by qy-liuhuo**
- Fixes #11199 

### Motivation

Add the `Grafana Loki` as a log management system to manage logs efficiently and centrally

### Modifications

- Added `opentelemetry-collector`, `Grafna` and `Loki` containers in the docker-compose
- Added the `loki.yaml` file to configure the Loki
- Optimized the `OpenTelemetryLogger`：
    - Added service.namespace and host.name configuration items 
    - Provided a Builder to help build OpenTelemetryLogger objects more conveniently

### Verifying this change

*(Please pick either of the following options)*

- [x] This change is a trivial rework/code cleanup without any test coverage.

- [ ] This change is already covered by existing tests, such as:
  *(please describe tests)*

- [ ] This change added tests and can be verified as follows:

  *(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Documentation

After running docker-compose, you can access Grafna Loki via `http://127.0.0.1:3000/explore`, and then you should query the corresponding sort logs by `service_name` or `service_namespace`.
image

Then You can see a list of logs and view detailed information by clicking on a specific log item.
image

### CODE REVIEW

**Review by aloyszhang — DISMISSED** [review]

**Comment by aloyszhang** [comment]
I found there are some duplicated modifications with #11070.
Please fix this problem if both of these two pull requests are needed

**Comment by qy-liuhuo** [comment]
> I found there are some duplicated modifications with #11070. Please fix this problem if both of these two pull requests are needed

Yeah，#11070 is just an example of usage， so i think we can temporarily close it（#11070）.

After this issue(#11199 ) is completed, We can raise a new issue to integrate for all connectors

**Comment by qy-liuhuo** [comment]
Due to new changes in #11212, this PR is closed and a new implementation will be provided later.

**Comment by qy-liuhuo** [comment]
This new commit make log reporting related containers optional：
When running docker-compose normally, only necessary containers will be started. 
If you need to enable the opentelemetry log reporting function of the Sort module, you can add the `--profile sort-report` option when starting, for example, `docker compose --profile sort-report up -d`

To support the profiles feature, we need to update the version setting of `docker-compose.yml` from `2.4` to `3.0`, and the `docker compose` version needs to be higher than `1.28.0`.

**Review by vernedeng — APPROVED** [review]

**Review by aloyszhang — APPROVED** [review]

**Comment by aloyszhang** [comment]
There is a problem in the workflow, please rebase the master branch to resolve it.

**Comment by qy-liuhuo** [comment]
> There is a problem in the workflow, please rebase the master branch to resolve it.

ok

**Comment by aloyszhang** [comment]
Unit test failed, details refer to https://github.com/apache/inlong/actions/runs/11284951233/job/31393310968?pr=11212

**Comment by qy-liuhuo** [comment]
> Unit test failed, details refer to https://github.com/apache/inlong/actions/runs/11284951233/job/31393310968?pr=11212

I got the error message: `java.lang.RuntimeException: ru.yandex.clickhouse.except.ClickHouseUnknownException: ClickHouse exception, code: 1002, host: localhost, port: 32772; localhost:32772 failed to respond
`, it seems ooks like a problem with the ckickhouse container.  Could you please restart the workflow for me?

**Comment by aloyszhang** [comment]
> I got the error message: `java.lang.RuntimeException: ru.yandex.clickhouse.except.ClickHouseUnknownException: ClickHouse exception, code: 1002, host: localhost, port: 32772; localhost:32772 failed to respond `, it seems ooks like a problem with the ckickhouse container. Could you please restart the workflow for me?

Sure, the failed check is re-running now

**Pull request merged**
