### PR TITLE
[INLONG-7533][Agent] Fix that log cannot be collected for position reset

### LINKED ISSUE #7533: [Improve][Agent] Log cannot be collected for position reset
### Description

Change agent log-level to INFO

### InLong Component

InLong Agent

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by doleyzi**
### Prepare a Pull Request
- [INLONG-7533][Agent] Change agent log-level to INFO

- Fixes #7533

### Motivation

*Reduce the amount of log debug log*

### CODE REVIEW

**Comment by dockerzhang** [comment]
@doleyzi please rebase the master before creating a new PR.

**Comment by healchow** [comment]
@doleyzi Hi, please refer this PR's comment, and reset to master brach again, thanks.

https://github.com/apache/inlong/pull/7403

**Comment by healchow** [comment]
> @doleyzi Hi, please refer this PR's comment, and reset to master brach again, thanks.
> 
> #7403

This PR has been pending for several days. In order to merge into the main branch for verification as soon as possible, I modified it.

If there are other commits later, please refer to the operation method described in the comment in the above PR, thank you.

**Review by healchow — APPROVED** [review]

**Review by dockerzhang — APPROVED** [review]

**Comment by doleyzi** [comment]
> @doleyzi Hi, please refer this PR's comment, and reset to master brach again, thanks.
> 
> #7403

thx

**Comment by doleyzi** [comment]
> > @doleyzi Hi, please refer this PR's comment, and reset to master brach again, thanks.
> > #7403
> 
> This PR has been pending for several days. In order to merge into the main branch for verification as soon as possible, I modified it.
> 
> @doleyzi If there are other commits later, please refer to the operation method described in the comment in the above PR, thank you.

thx

**Pull request merged**
