### PR TITLE
[INLONG-11002][SDK] Transform SQL support Fibonacci function

### LINKED ISSUE #11002: [Feature][SDK] Transform SQL support Fibonacci function
### Description

parent issue [Umbrella] Tencent Rhino-bird: Expand InLong Transform functions #10796 
definition of Fibonacci sequence:
F(0) = 0
F(1) = 1
对于 n >= 2，F(n) = F(n-1) + F(n-2)
F(2) = 1 （1 = 1 + 0）
F(3) = 2 （2 = 1 + 1）
F(4) = 3 （3 = 2 + 1）
fibonacci(numeric)--returns the nth Fibonacci number
examples:
fibonacci(0) = 0
fibonacci(4) = 3

### Use case

_No response_

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by youzhi886**
Fixes #11002 
**Motivation**
Add one arithmetic function classes:FibonacciFunction. Also, add the corresponding unit test codes

### CODE REVIEW

**Comment by luchunliang** [comment]
Please use annotation to resolve conflicting file.

**Comment by luchunliang** [comment]
Please use independent UT class file to avoid UT conflicting file.

**Comment by emptyOVO** [comment]
this pr will be closed for #11622 to complete

**Comment by emptyOVO** [comment]
this pr will be closed for #11622 to complete

**Pull request closed without merging**
