### PR TITLE
[INLONG-5178][Manager] Optimize Warning info for the Manager module

### PR DESCRIPTION
**Pull request by liangyepianzhou**
### Prepare a Pull Request
- Fixes  https://github.com/apache/inlong/issues/5178
### Motivation

Optimize Warning info when compiling the Manager module
### Modifications

Optimize Warning info when compiling the Manager module

### Verifying this change

- [x] This change is a trivial rework/code cleanup without any test coverage.

### CODE REVIEW

**Comment by liangyepianzhou** [comment]
@dockerzhang Could you please take a look when you have time?

**Comment by dockerzhang** [comment]
@liangyepianzhou there are failed UTs. Please check again.

**Comment by liangyepianzhou** [comment]
The `Builder.Default` is not appended into InlongPulsarInfo.
Because its method genRequest needs to copy properties. if it adds `@Builder.Default`, the variables will get null.

>     @Override
>     public InlongPulsarRequest genRequest() {
>         return CommonBeanUtils.copyProperties(this, InlongPulsarRequest::new);
>     }

**Comment by dockerzhang** [comment]
@liangyepianzhou there still are lots of warnings for `Builder.Default`. Please check the [workflow](https://github.com/apache/inlong/runs/7486656498?check_suite_focus=true) again.

**Comment by dockerzhang** [comment]
```
[INFO] Compiling 332 source files to /home/runner/work/inlong/inlong/inlong-manager/manager-common/target/classes
Warning:  /home/runner/work/inlong/inlong/inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/group/pulsar/InlongPulsarInfo.java:[55,20] @SuperBuilder will ignore the initializing expression entirely. If you want the initializing expression to serve as default, add @Builder.Default. If it is not supposed to be settable during building, make the field final.
Warning:  /home/runner/work/inlong/inlong/inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/group/pulsar/InlongPulsarInfo.java:[58,17] @SuperBuilder will ignore the initializing expression entirely. If you want the initializing expression to serve as default, add @Builder.Default. If it is not supposed to be settable during building, make the field final.
Warning:  /home/runner/work/inlong/inlong/inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/group/pulsar/InlongPulsarInfo.java:[61,21] @SuperBuilder will ignore the initializing expression entirely. If you want the initializing expression to serve as default, add @Builder.Default. If it is not supposed to be settable during building, make the field final.
Warning:  /home/runner/work/inlong/inlong/inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/group/pulsar/InlongPulsarInfo.java:[64,21] @SuperBuilder will ignore the initializing expression entirely. If you want the initializing expression to serve as default, add @Builder.Default. If it is not supposed to be settable during building, make the field final.
Warning:  /home/runner/work/inlong/inlong/inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/group/pulsar/InlongPulsarInfo.java:[67,21] @SuperBuilder will ignore the initializing expression entirely. If you want the initializing expression to serve as default, add @Builder.Default. If it is not supposed to be settable during building, make the field final.
Warning:  /home/runner/work/inlong/inlong/inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/group/pulsar/InlongPulsarInfo.java:[70,21] @SuperBuilder will ignore the initializing expression entirely. If you want the initializing expression to serve as default, add @Builder.Default. If it is not supposed to be settable during building, make the field final.
Warning:  /home/runner/work/inlong/inlong/inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/group/pulsar/InlongPulsarInfo.java:[73,20] @SuperBuilder will ignore the initializing expression entirely. If you want the initializing expression to serve as default, add @Builder.Default. If it is not supposed to be settable during building, make the field final.
Warning:  /home/runner/work/inlong/inlong/inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/group/pulsar/InlongPulsarInfo.java:[76,21] @SuperBuilder will ignore the initializing expression entirely. If you want the initializing expression to serve as default, add @Builder.Default. If it is not supposed to be settable during building, make the field final.
Warning:  /home/runner/work/inlong/inlong/inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/group/pulsar/InlongPulsarInfo.java:[79,20] @SuperBuilder will ignore the initializing expression entirely. If you want the initializing expression to serve as default, add @Builder.Default. If it is not supposed to be settable during building, make the field final.
Warning:  /home/runner/work/inlong/inlong/inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/group/pulsar/InlongPulsarInfo.java:[82,21] @SuperBuilder will ignore the initializing expression entirely. If you want the initializing expression to serve as default, add @Builder.Default. If it is not supposed to be settable during building, make the field final.
Warning:  /home/runner/work/inlong/inlong/inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/group/pulsar/InlongPulsarInfo.java:[85,20] @SuperBuilder will ignore the initializing expression entirely. If you want the initializing expression to serve as default, add @Builder.Default. If it is not supposed to be settable during building, make the field final.
```

**Comment by liangyepianzhou** [comment]
> ```
> [INFO] Compiling 332 source files to /home/runner/work/inlong/inlong/inlong-manager/manager-common/target/classes
> Warning:  /home/runner/work/inlong/inlong/inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/group/pulsar/InlongPulsarInfo.java:[55,20] @SuperBuilder will ignore the initializing expression entirely. If you want the initializing expression to serve as default, add @Builder.Default. If it is not supposed to be settable during building, make the field final.
> Warning:  /home/runner/work/inlong/inlong/inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/group/pulsar/InlongPulsarInfo.java:[58,17] @SuperBuilder will ignore the initializing expression entirely. If you want the initializing expression to serve as default, add @Builder.Default. If it is not supposed to be settable during building, make the field final.
> Warning:  /home/runner/work/inlong/inlong/inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/group/pulsar/InlongPulsarInfo.java:[61,21] @SuperBuilder will ignore the initializing expression entirely. If you want the initializing expression to serve as default, add @Builder.Default. If it is not supposed to be settable during building, make the field final.
> Warning:  /home/runner/work/inlong/inlong/inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/group/pulsar/InlongPulsarInfo.java:[64,21] @SuperBuilder will ignore the initializing expression entirely. If you want the initializing expression to serve as default, add @Builder.Default. If it is not supposed to be settable during building, make the field final.
> Warning:  /home/runner/work/inlong/inlong/inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/group/pulsar/InlongPulsarInfo.java:[67,21] @SuperBuilder will ignore the initializing expression entirely. If you want the initializing expression to serve as default, add @Builder.Default. If it is not supposed to be settable during building, make the field final.
> Warning:  /home/runner/work/inlong/inlong/inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/group/pulsar/InlongPulsarInfo.java:[70,21] @SuperBuilder will ignore the initializing expression entirely. If you want the initializing expression to serve as default, add @Builder.Default. If it is not supposed to be settable during building, make the field final.
> Warning:  /home/runner/work/inlong/inlong/inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/group/pulsar/InlongPulsarInfo.java:[73,20] @SuperBuilder will ignore the initializing expression entirely. If you want the initializing expression to serve as default, add @Builder.Default. If it is not supposed to be settable during building, make the field final.
> Warning:  /home/runner/work/inlong/inlong/inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/group/pulsar/InlongPulsarInfo.java:[76,21] @SuperBuilder will ignore the initializing expression entirely. If you want the initializing expression to serve as default, add @Builder.Default. If it is not supposed to be settable during building, make the field final.
> Warning:  /home/runner/work/inlong/inlong/inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/group/pulsar/InlongPulsarInfo.java:[79,20] @SuperBuilder will ignore the initializing expression entirely. If you want the initializing expression to serve as default, add @Builder.Default. If it is not supposed to be settable during building, make the field final.
> Warning:  /home/runner/work/inlong/inlong/inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/group/pulsar/InlongPulsarInfo.java:[82,21] @SuperBuilder will ignore the initializing expression entirely. If you want the initializing expression to serve as default, add @Builder.Default. If it is not supposed to be settable during building, make the field final.
> Warning:  /home/runner/work/inlong/inlong/inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/group/pulsar/InlongPulsarInfo.java:[85,20] @SuperBuilder will ignore the initializing expression entirely. If you want the initializing expression to serve as default, add @Builder.Default. If it is not supposed to be settable during building, make the field final.
> ```

@dockerzhang  
I have commented that the [inlongPulsarinfo](https://github.com/apache/inlong/pull/5186#issuecomment-1193273042) will not add @Builder.Default.

**Review by kipshi — APPROVED** [review]

**Review by dockerzhang — APPROVED** [review]

**Review by healchow — APPROVED** [review]
LGTM

**Pull request merged**
