### PR TITLE
[INLONG-5560][Sdk] Replace all InLong to Inlong

### LINKED ISSUE #5560: [Feature] Replace all "InLong" to "Inlong"
### Description

_No response_

### Use case

_No response_

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by vernedeng**
### Prepare a Pull Request

- Fixes #5560 

### Motivation

*Explain here the context, and why you're making that change. What is the problem you're trying to solve?*

### Modifications

Replace all "InLong" to "Inlong" in SortSdk

### Verifying this change

*(Please pick either of the following options)*

- [x] This change is a trivial rework/code cleanup without any test coverage.

  *(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
  - If a feature is not applicable for documentation, explain why?
  - If a feature is not documented yet in this PR, please create a follow-up issue for adding the documentation

### CODE REVIEW

**Comment by dockerzhang** [comment]
@vernedeng I think `InLong` is right, and it's no need to change it.

**Review by EMsnap — APPROVED** [review]

**Comment by vernedeng** [comment]
> @vernedeng I think `InLong` is right, and it's no need to change it.

@dockerzhang some contributors insist to unify valuables to **_inlong_** and **_Inlong_** 👀

**Review by doleyzi — APPROVED** [review]

**Review by luchunliang — APPROVED** [review]
LGTM

**Comment by vernedeng** [comment]
In order to reduce risk,  we decide to gradually repair these naming problems in each PR

**Pull request closed without merging**
