### PR TITLE
[INLONG-4719][All] Remove commons-lang 2.6 dependency for all modules

### LINKED ISSUE #4719: [Improve] remove commons-lang 2.6 dependency
### Description

use commons-lang3

### InLong Component

InLong Manager, InLong Agent, InLong DataProxy, InLong SDK, InLong TubeMQ, InLong Sort, InLong Audit

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by ningpp**
Fixes #4719

### CODE REVIEW

**Comment by dockerzhang** [comment]
@ningpp there workflows failed, please fix it and change the license file at the same time.

**Review by healchow — APPROVED** [review]
LGTM

**Comment by healchow** [comment]
Please refer the license and notice guide: https://inlong.apache.org/community/how-to-maintain-3rd-party-dependencies

**Comment by ningpp** [comment]
@healchow  what should i do?

**Comment by healchow** [comment]
> @healchow what should i do?

@ningpp Hi, I did not find your email or other contact info. Can you send an email to me?

My email address is: [healchow@apache.org](mailto:healchow@apache.org)

**Comment by ningpp** [comment]
already send a email to you @healchow

**Comment by healchow** [comment]
> already send a email to you @healchow

OK, let's talk in IM.

**Comment by ningpp** [comment]
other library denpend commons-lang 2.6,

apache-inlong-manager-web-xxx-bin.tar.gz will contain commons-lang 2.6

do i need delete license in licenses folder

**Comment by dockerzhang** [comment]
@ningpp that's ok to me. thanks.

**Review by dockerzhang — APPROVED** [review]

**Review by healchow — APPROVED** [review]

**Pull request merged**
