### PR TITLE
[INLONG-7734][Dashboard] Support new layout design & dark theme

### LINKED ISSUE #7734: [Feature][Dashboard] Update Dashbaord layout & folder design
### Description

- Use the new left-right layout form
- File system design using core/ui separation, and support dark theme

### Use case

_No response_

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by leezng**
- Fixes #7734

image

image

### CODE REVIEW

**Comment by dockerzhang** [comment]
@leezng please add an image to show the effect.

**Review by bluewang — APPROVED** [review]

**Comment by healchow** [comment]
Is there too much space at the top?

image

**Comment by leezng** [comment]
> Is there too much space at the top?
> 
> image

There is a reserved breadcrumb position on the right.

**Comment by leezng** [comment]
> Does it support the response layout? To support small screens or zooming conditions

Supported. The sidebar is collapsible.

**Comment by aloyszhang** [comment]
image

It's better to keep consistency for all these prompts. 
How about removing the suffix `Count`?

**Comment by leezng** [comment]
> 

All characters have not been modified, this modification only involves the core layer of the code.

**Comment by healchow** [comment]
> All characters have not been modified, this modification only involves the core layer of the code.

If there are other functions or optimizations, such as remove the suffix `Count`, it is recommended to submit a new PR to update. @aloyszhang cc

**Review by healchow — APPROVED** [review]
LGTM

**Comment by aloyszhang** [comment]
> > 
> 
> All characters have not been modified, this modification only involves the core layer of the code.

Make sense to me.

**Review by aloyszhang — APPROVED** [review]

**Review by dockerzhang — APPROVED** [review]

**Pull request merged**
