### PR TITLE
[INLONG-4751][Sort] Optimize the metadata implementation of Extract Nodes and Load Nodes

### LINKED ISSUE #4751: [Improve][Sort] Optimize the metadata implementation of Extract Nodes and Load Nodes
### Description

Optimize the metadata implementation of Extract Nodes and Load Nodes.

### InLong Component

InLong Sort

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by yunqingmoswu**
### Prepare a Pull Request
*(Change the title refer to the following example)*

- Title: [INLONG-4685][Sort] Optimize the metadata implementation of Extract Nodes and Load Nodes

*(The following *XYZ* should be replaced by the actual [GitHub Issue](https://github.com/apache/inlong/issues) number)*

Fixes #4751 

### Motivation

Optimize the metadata implementation of Extract Nodes and Load Nodes:
1. Decouple node-supported metadata fields from Flink SQL Parser. Node update metadata field support without modifying Flink SQL Parser.
2. Increase the scalability of metadata field support. To support metadata fields, new nodes only need to implement the Metadata interface.

### Modifications

The metadata implementation of Extract Nodes and Load Nodes will be more elegant.

### Verifying this change

*(Please pick either of the following options)*

- [ ] This change is a trivial rework/code cleanup without any test coverage.

- [x] This change is already covered by existing tests, such as:
  *(please describe tests)*

- [ ] This change added tests and can be verified as follows:

  *(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
  - If a feature is not applicable for documentation, explain why?
  - If a feature is not documented yet in this PR, please create a follow-up issue for adding the documentation

### CODE REVIEW

**Comment by yunqingmoswu** [comment]
1. Decouple node-supported metadata fields from Flink SQL Parser. Node update metadata field support without modifying Flink SQL Parser.
2. Increase the scalability of metadata field support. To support metadata fields, new nodes only need to implement the Metadata interface.

**Review by gong — APPROVED** [review]

**Comment by gong** [comment]
LGTM

**Review by healchow — APPROVED** [review]

**Review by Oneal65 — APPROVED** [review]

**Comment by thesumery** [comment]
LGTM

**Review by GanfengTan — APPROVED** [review]

**Review by EMsnap — APPROVED** [review]
LGTM

**Pull request merged**
