### PR TITLE
[INLONG-7218][CI] Add Windows and MacOS support on GitHub Actions

### LINKED ISSUE #7218: [Feature][CI] Add Windows support on GitHub Actions when building and testing InLong
### Description

We can use `jobs.<job_id>.runs-on` to define the type of machine to run the job on.

See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idruns-on

### Use case

_No response_

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by shink**
Fixes #7218

### Motivation

We can use `jobs.<job_id>.runs-on` to define the type of machine to run the job on.

See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idruns-on

Reference: https://stackoverflow.com/questions/59295795/run-github-action-on-multiple-environments

### Modifications

Add Windows and MacOS support on GitHub Actions when building and testing InLong.

### CODE REVIEW

**Comment by shink** [comment]
@dockerzhang Windows, Linux and MacOS are all available GitHub-hosted runner types. Should we support MacOS on GitHub Actions?

**Comment by dockerzhang** [comment]
@shink it's better to add the action for MacOS. Thanks.

**Review by healchow — APPROVED** [review]

**Review by healchow — APPROVED** [review]

**Comment by shink** [comment]
@dockerzhang PTAL.

**Comment by dockerzhang** [comment]
@shink, the CI workflow run failed for windows os. Please fix it.
image

**Comment by shink** [comment]
@dockerzhang

It seems that there are some codes that do not support cross-platform.

See https://github.com/shink/inlong/actions/runs/4097168091/jobs/7065344093#step:6:2138

```
File.separator is used as a regex; will not work on Windows.
```
image

**Comment by shink** [comment]
@dockerzhang PTAL

**Review by healchow — APPROVED** [review]

**Pull request closed without merging**
