### PR TITLE
[INLONG-8653][Sort] Fix the query sql for jdbc sink postgres dialect multiple table scenerios. 

### LINKED ISSUE #8653: [Bug][Sort] fix the query sql for jdbc pg dialect multiple table scenerios.
### What happened

We have client reports that pg-pg multiple table scenerios would fail on certain versions of postgres, since .

    private static final String QUERY_PRIMARY_KEY_SQL = "SELECT\n" +
            "\tstring_agg (DISTINCT t3.attname, ',') AS " + PRIMARY_KEY_COLUMN + ",\n" +
            "    \tt4.tablename AS tableName\n" +
            "FROM\n" +
            "\tpg_constraint t1\n" +
            "INNER JOIN pg_class t2 ON t1.conrelid = t2.oid\n" +
            "INNER JOIN pg_attribute t3 ON t3.attrelid = t2.oid\n" +
            "AND array_position (t1.conkey, t3.attnum) is not null\n" +
            "INNER JOIN pg_tables t4 on t4.tablename = t2.relname\n" +
            "INNER JOIN pg_index t5 ON t5.indrelid = t2.oid\n" +
            "AND t3.attnum = ANY (t5.indkey)\n" +
            "LEFT JOIN pg_description t6 on t6.objoid = t3.attrelid\n" +
            "and t6.objsubid = t3.attnum\n" +
            "WHERE\n" +
            "\tt1.contype = 'p'\n" +
            "AND length (t3.attname) > 0\n" +
            "AND t2.oid = ?::regclass\n" +
            "group by\n" +
            "\tt4.tablename";

企业微信截图_a78c27f6-f7d2-4158-a46c-dc5d524b9bbd

### What you expected to happen

the query sql should be compatible with most versions of postgres.

### How to reproduce

the problem is specific to some version of postgres. My edited sql should be strictly MORE compatible than the old one. It is tested in the production environment by the client via a hotfix (many hotfixes, actually). So it should not produce any errors.

The new sql is :     private static final String QUERY_PRIMARY_KEY_SQL = "SELECT\n"
            + " string_agg(pg_attribute.attname, ',') AS pkColumn,\n"
            + " pg_class.relname AS tableName\n"
            + "            FROM\n"
            + "    pg_index, pg_class, pg_attribute\n"
            + "            WHERE\n"
            + "    pg_class.oid = ?::regclass AND\n"
            + "    indrelid = pg_class.oid AND\n"
            + "    pg_attribute.attrelid = pg_class.oid AND\n"
            + "    pg_attribute.attnum = any(pg_index.indkey) AND\n"
            + "    indisprimary \n "
            + "    GROUP BY \n"
            + "    pg_class.relname, pg_index.indkey;";

it does the same function,  but is more robust and compatible.

(the current syncwithgithub version is this one)

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Sort

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by Yizhou-Yang**
### Prepare a Pull Request
- Fixes #8653 

### Motivation
plz refer to issue

### Modifications
adjusted the sql.

### Verifying this change
This change is used in the production environment.

### CODE REVIEW

**Comment by gong** [comment]
The title is error. This is not pg cdc, it is improve for sink to pg. @Yizhou-Yang

**Review by gong — COMMENTED** [review]
Is it compatible with regular pg databases?

**Comment by Yizhou-Yang** [comment]
> Is it compatible with regular pg databases?

Fixed title. It is compatible with regular pg, as indicated by the comment above.

**Comment by gong** [comment]
> 

@Yizhou-Yang The issue description need modfiy, not cdc pg.

**Review by EMsnap — APPROVED** [review]

**Review by gong — APPROVED** [review]

**Pull request merged**
