### PR TITLE
[INLONG-10091][Agent] Delete the useless code related to 8008 listen port

### LINKED ISSUE #10091: [Feature][Sort] Add json format for 1.18
### Description

add support of JSON format for 1.18

### Use case

_No response_

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by justinwwhuang**
Fixes #10091

### Motivation
The agent does not listen to the port, and the relevant code is useless
### Modifications

Delete useless code

### Verifying this change

*(Please pick either of the following options)*

- [x] This change is a trivial rework/code cleanup without any test coverage.

- [ ] This change is already covered by existing tests, such as:
  *(please describe tests)*

- [ ] This change added tests and can be verified as follows:

  *(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Documentation

No doc needed

### CODE REVIEW

**Comment by dockerzhang** [comment]
please remove https://github.com/apache/inlong/blob/master/docker/docker-compose/docker-compose.yml#L102-L103 and https://github.com/apache/inlong/blob/master/inlong-agent/agent-docker/Dockerfile#L30

**Comment by justinwwhuang** [comment]
> please remove https://github.com/apache/inlong/blob/master/docker/docker-compose/docker-compose.yml#L102-L103 and https://github.com/apache/inlong/blob/master/inlong-agent/agent-docker/Dockerfile#L30

done

**Review by dockerzhang — APPROVED** [review]

**Comment by EMsnap** [comment]
public static final String AGENT_ENABLE_HTTP = "agent.http.enable";
 public static final boolean DEFAULT_AGENT_ENABLE_HTTP = false; these codes should also be deleted

**Comment by EMsnap** [comment]
Please update https://inlong.apache.org/docs/next/modules/agent/configure

**Comment by dockerzhang** [comment]
> Please update https://inlong.apache.org/docs/next/modules/agent/configure

updated in https://github.com/apache/inlong-website/pull/955

**Review by dockerzhang — APPROVED** [review]

**Pull request merged**
