### PR TITLE
[INLONG-7508][Sort] Carry right RowKind when cdc-base sends RowData to sink

### LINKED ISSUE #7508: [Improve][Sort] Carry right RowKind when cdc-base sends RowData to sink
### Description

cdc-base sends RowData to sink, should carry right RowKind.

image
image
image

### Use case

_No response_

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by liaorui**
### Prepare a Pull Request
*(Change the title refer to the following example)*

- Title Example: [INLONG-XYZ][Component] Title of the pull request

*(The following *XYZ* should be replaced by the actual [GitHub Issue](https://github.com/apache/inlong/issues) number)*

- Fixes #7508

### Motivation

*Explain here the context, and why you're making that change. What is the problem you're trying to solve?*

cdc-base sends RowData to sink, should carry right RowKind

image
image
image

### Modifications

*Describe the modifications you've done.*

`AppendMetadataCollector` make a new GenericRowData instance, should pass right RowKind.

### Verifying this change

*(Please pick either of the following options)*

- [ ] This change is a trivial rework/code cleanup without any test coverage.

- [ ] This change is already covered by existing tests, such as:
  *(please describe tests)*

- [ ] This change added tests and can be verified as follows:

  *(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
  - If a feature is not applicable for documentation, explain why?
  - If a feature is not documented yet in this PR, please create a follow-up issue for adding the documentation

### CODE REVIEW

**Comment by gong** [comment]
Now sink parse rowkind from data when all database migration. So rowkind use INSERT.

**Comment by liaorui** [comment]
> 
Source database has a update operation,  cdc send `update` type in json data.  Sink connector cannot known whether is Update_Before or Update_After. 

The 3rd screenshot shows that sink connector always get update before node null from json data.

**Review by healchow — APPROVED** [review]

**Comment by gong** [comment]
> > 
> 
> When source table has a update operation, cdc send `update` type in json data. Sink connector cannot known whether is Update_Before or Update_After.
> 
> The 3rd screenshot shows that sink connector always get `updateBeforeNode` null from json data.

@liaorui @EMsnap have a PR issue this problem. https://github.com/apache/inlong/issues/7397

**Comment by EMsnap** [comment]
The opType in allmigrate is represented as the parameter TYPE in canal json. maybe you can get the optype from there

**Comment by liaorui** [comment]
Close this PR since PR #7397 has solved this problem.

**Pull request closed without merging**
