### PR TITLE
[INLONG-6908][Sort] support all rowkinds for metric computing for jdbc connector

### LINKED ISSUE #6908: [Feature] support all rowkinds for metric computing for es connector
### Description

[Feature] support all rowkinds for metric computing for es connector

### Use case

[Feature] support all rowkinds for metric computing for es connector

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by EMsnap**
### Prepare a Pull Request

- Fixes #6908 

### Motivation

[INLONG-6908][Sort] support all rowkinds for metric computing for jdbc connector

### Modifications

[INLONG-6908][Sort] support all rowkinds for metric computing for jdbc connector

### Documentation

  - Does this pull request introduce a new feature? (yes / no)

### CODE REVIEW

**Comment by gong** [comment]
lost dirty data metric restore

**Comment by gong** [comment]
```java
  
            if (executionOptions.getBatchSize() > 0
                    && batchCount >= executionOptions.getBatchSize()) {
                flush();
                if (sinkMetricData != null) {
                    sinkMetricData.invoke(rowSize, dataSize);
                }
                resetStateAfterFlush();
            }
        } catch (Exception e) {
            if (sinkMetricData != null) {
                sinkMetricData.invokeDirty(rowSize, dataSize);
            }
            resetStateAfterFlush();
            throw new IOException("Writing records to JDBC failed.", e);
        }
```
It should not to throw exception when computing dirty data metric. And we can add judgement by ignore dirty option. @yunqingmoswu review here

**Comment by gong** [comment]
work is Intersecting with https://github.com/apache/inlong/pull/6752

**Comment by EMsnap** [comment]
> work is Intersecting with #6752

OK, will continue this pr after dirty sink is finished, stil has some problem there

**Pull request closed without merging**
